### ISSUE TITLE
MSIX signing rejects escaped distinguished names (DNs)

### ISSUE THREAD

**Issue by alwaysbemark** [ebourg/jsign#256]
jsign compares the certificate DN name to the `Publisher` attribute of the AppxManifest file.

Our cert subject name looks like this: `CN=COMPANY, INC.,O=COMPANY, INC.,L=New York,ST=New York,C=US`
This contains commas which needs to be escaped. The only way this can be represented in the Appx manifest XML (due to the need to quote the individual components in XML):

`<Identity ... Publisher="CN=&quot;COMPANY, INC.&quot;, O=&quot;COMPANY, INC.&quot;, L=New York, S=New York, C=US" ...>`

When trying to sign with jsign, the following message is shown:

`jsign: improperly specified input name: CN=&quot;COMPANY, INC.&quot;,O=&quot;COMPANY, INC.&quot;, L=New York,ST=New York, C=US`

There seem to be a few issues:
1. The `quot` escape characters aren't being decoded as real quotes
2. Some spaces between the components (CN,O,S,C) are retained, some aren't in the jsign input name - this may be OK if the check ignores spaces and doesn't do a direct string comparison
3. `S` becomes `ST`, though I think that may be OK as long as jsign treats them as one and the same in this check

I think this, in practice, means that we can't sign MSIX bundles where any of the DN components has a comma or another character that needs to be escaped. Escaping with `\,` or `\2C` doesn't pass the manifest XML regex check, so `&quot;`'ing around the values seems like the only way forward.

Could it be that https://github.com/ebourg/jsign/blob/de54040452141d321e2bc2e7d1a30a6d869975ba/jsign-core/src/main/java/net/jsign/appx/APPXFile.java#L202 isn't robust enough or that escape sequences and quotes aren't treated appropriately? 

Thanks in advance!

**Comment by ebourg** [comment]
Thank you for reporting this issue. The S/ST mismatch and the white space issue were fixed recently (793cda6828212bbb7a59bb1872746d6b7e2e79a6, ccb1e8089b31bbc02b5426a68615fabaf9223480). Jsign delegates to `javax.security.auth.x500.X500Principal` for parsing and putting the DN in a canonical form before comparing, so the spaces and the order of the fields shouldn't matter. However the Publisher attribute isn't read with an XML parser and the `&quot;` entities aren't unescaped. I'll fix that.

**Comment by ebourg** [comment]
@alwaysbemark I've pushed a modification to unescape the XML entities in the publisher field. Could you check if that fixes the issue please?

**Comment by alwaysbemark** [comment]
Hey @ebourg ! Thanks for the quick turnaround. The escaping works but I still see some dependence on the order of DN components:

`jsign: The app manifest publisher name (C=US, S=New York, L=New York, O="COMPANY, INC.", CN="COMPANY, INC.") must match the subject name of the signing certificate (CN=COMPANY\, INC.,O=COMPANY\, INC.,L=New York,ST=New York,C=US)`

By simple re-arranging the DN components I was able to work around this issue and sign successfully but it still seems like the order is enforced somewhere it shouldn't be.
Thank you!

**Comment by ebourg** [comment]
The order of the components is now ignored, and the different cases are fully test covered. I hope I got it right this time :) Thank you for the help.

**Comment by alwaysbemark** [comment]
Thank you!
